config/routes.rb
Rails.application.routes.draw do
  get 'depts/index'
 root 'depts#index'
  resources :depts do 
    member do 
	    get :employee_list
	end
  end	
 resources :emps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dept.rb
class Dept < ApplicationRecord
   has_many :emps
   
	def self.search(search)
		if search
			where(id: search)
		else
			self.all
		end
	end
end

app/models/emp.rb
class Emp < ApplicationRecord
 validates_presence_of :name
 validates_presence_of :dept_id, message:  "please select dept"
 belongs_to :dept
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  def index
     unless  params[:serach].present? 
        @depts =  Dept.search(params[:search])
	  else
	     @depts =  Dept.all  
      end	  
  end
  
   def employee_list
      @emps = Emp.where(dept_id: params[:id])
	    respond_to do |format|
			format.html 
			format.js
        end
   end
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  before_action :set_emp, only: [:show, :edit, :update, :destroy]

  # GET /emps
  # GET /emps.json
  def index
    @emps = Emp.all
  end

  # GET /emps/1
  # GET /emps/1.json
  def show
  end

  # GET /emps/new
  def new
    @emp = Emp.new
  end

  # GET /emps/1/edit
  def edit
  end

  # POST /emps
  # POST /emps.json
  def create
    @emp = Emp.new(emp_params)

    respond_to do |format|
      if @emp.save
        format.html { redirect_to @emp, notice: 'Emp was successfully created.' }
        format.json { render :show, status: :created, location: @emp }
      else
        format.html { render :new }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emps/1
  # PATCH/PUT /emps/1.json
  def update
    respond_to do |format|
      if @emp.update(emp_params)
        format.html { redirect_to @emp, notice: 'Emp was successfully updated.' }
        format.json { render :show, status: :ok, location: @emp }
      else
        format.html { render :edit }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1
  # DELETE /emps/1.json
  def destroy
    @emp.destroy
    respond_to do |format|
      format.html { redirect_to emps_url, notice: 'Emp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp
      @emp = Emp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emp_params
      params.require(:emp).permit(:name, :dept_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/views/depts/_employee_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Emps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dept</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emps.each do |emp| %>
      <tr>
        <td><%= emp.name %></td>
        <td><%= emp.dept.name %></td>
        <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
        <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Departments", depts_path%>

app/views/depts/employee_list.js.erb
$("#main").html("<%= escape_javascript(render :partial => 'depts/employee_list') %>");

app/views/depts/index.html.erb
<div id="main">

<%= form_tag depts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>


<p id="notice"><%= notice %></p>

<h1>Depts</h1>

<table>
  <thead>
    <tr>
	<th> Id </th>
      <th>Name</th>
	  <th>Show Employees</th>
	  <th>Add New Employees</th>
    </tr>
  </thead>

  <tbody>
    <% @depts.each do |dept| %>
      <tr>
	    <td><%= dept.try(:id) %></td>
        <td><%= dept.try(:name) %></td>
        <td><%= link_to 'Show Employees', employee_list_dept_path(dept), remote: true %></td>
		<td><%= link_to  'Add Employee',  new_emp_path %>  </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= link_to 'Departments', depts_index_path %>
</div>

app/views/emps/_form.html.erb
<%= form_for(emp) do |f| %>
  <% if emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% emp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :dept_id %>
    <%= f.collection_select :dept_id, Dept.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emps/edit.html.erb
<h1>Editing Emp</h1>

<%= render 'form', emp: @emp %>

<%= link_to 'Show', @emp %> |
<%= link_to 'Back', emps_path %>

app/views/emps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dept</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emps.each do |emp| %>
      <tr>
        <td><%= emp.name %></td>
        <td><%= emp.dept_id %></td>
        <td><%= link_to 'Show', emp %></td>
        <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
        <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp', new_emp_path %>|   <%= link_to 'Departments', depts_index_path %>

app/views/emps/new.html.erb
<h1>Add New Emp</h1>

<%= render 'form', emp: @emp %>

<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emp.name %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @emp.dept_id %>
</p>

<%= link_to 'Edit', edit_emp_path(@emp) %> |
<%= link_to 'Back', emps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssignmentApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>